import { useMutation } from "@tanstack/react-query";
import { useEffect, useState } from "react";

import {
  PLAYER_PROFILE_TIERS,
  updatePlayerProfile,
  type PlayerProfile,
  type PlayerProfileFieldName
} from "../lib/api";

type SaveState = "idle" | "saving" | "saved" | "error";

interface ProfileEditorProps {
  profile: PlayerProfile;
  onSaved: (updatedProfile: PlayerProfile) => void;
  saveProfile?: typeof updatePlayerProfile;
}

function badgeForProfile(profile: PlayerProfile): string {
  if (profile.generated_by === "llm-extraction-failed") {
    return "Extraction failed";
  }

  return profile.edited ? "Curated" : "Un-curated";
}

export function ProfileEditor({
  profile,
  onSaved,
  saveProfile = updatePlayerProfile
}: ProfileEditorProps) {
  const [values, setValues] = useState<Record<PlayerProfileFieldName, string>>({
    tier: profile.tier,
    role_2004_05: profile.role_2004_05 ?? "",
    qualitative_descriptor: profile.qualitative_descriptor ?? ""
  });
  const [saveState, setSaveState] = useState<SaveState>("idle");
  const [fieldError, setFieldError] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  useEffect(() => {
    setValues({
      tier: profile.tier,
      role_2004_05: profile.role_2004_05 ?? "",
      qualitative_descriptor: profile.qualitative_descriptor ?? ""
    });
  }, [profile]);

  const mutation = useMutation({
    mutationFn: (input: { fieldName: PlayerProfileFieldName; value: string | null }) =>
      saveProfile(profile.player_id, {
        profile_version: profile.profile_version,
        changes: {
          [input.fieldName]: input.value
        }
      }),
    onMutate: () => {
      setSaveState("saving");
      setSaveError(null);
    },
    onSuccess: (updatedProfile) => {
      setSaveState("saved");
      onSaved(updatedProfile);
    },
    onError: (error) => {
      setSaveState("error");
      setSaveError(error instanceof Error ? error.message : "Save failed");
    }
  });

  function saveField(fieldName: PlayerProfileFieldName): void {
    const rawValue = values[fieldName];
    const normalisedValue = fieldName === "tier" ? rawValue : rawValue.trim() || null;
    const currentValue = profile[fieldName] ?? "";

    if (fieldName === "tier" && !PLAYER_PROFILE_TIERS.includes(rawValue as PlayerProfile["tier"])) {
      setFieldError("Tier must be S, A, B, C, or D.");
      return;
    }

    setFieldError(null);

    if (normalisedValue === currentValue || (normalisedValue === null && currentValue === "")) {
      return;
    }

    mutation.mutate({ fieldName, value: normalisedValue });
  }

  return (
    <section className="admin-panel" aria-label="Player profile editor">
      <h2>Player Profile (LLM-extracted)</h2>
      <p>
        <span className="admin-badge">{badgeForProfile(profile)}</span>{" "}
        <span className="admin-muted">
          Generated by {profile.generated_by} at {profile.generated_at}
        </span>
      </p>
      <p className="admin-muted">Blur a field to save that value.</p>
      <div className="admin-form">
        <label>
          Tier
          <select
            aria-label="Tier"
            value={values.tier}
            onBlur={() => saveField("tier")}
            onChange={(event) => setValues((current) => ({ ...current, tier: event.target.value }))}
          >
            {PLAYER_PROFILE_TIERS.map((tier) => (
              <option key={tier} value={tier}>
                {tier}
              </option>
            ))}
          </select>
        </label>
        <label>
          Role 2004/05
          <textarea
            aria-label="Role 2004/05"
            rows={3}
            value={values.role_2004_05}
            onBlur={() => saveField("role_2004_05")}
            onChange={(event) =>
              setValues((current) => ({ ...current, role_2004_05: event.target.value }))
            }
          />
        </label>
        <label>
          Qualitative descriptor
          <textarea
            aria-label="Qualitative descriptor"
            rows={5}
            value={values.qualitative_descriptor}
            onBlur={() => saveField("qualitative_descriptor")}
            onChange={(event) =>
              setValues((current) => ({
                ...current,
                qualitative_descriptor: event.target.value
              }))
            }
          />
        </label>
      </div>
      <p>Status: {saveState}</p>
      {fieldError ? <p className="admin-error">{fieldError}</p> : null}
      {saveError ? <p className="admin-error">{saveError}</p> : null}
    </section>
  );
}
