-- Persisted match-engine workbench run history.
--
-- Additive only: stores metadata for artefacts generated by the standalone
-- match engine workbench.

PRAGMA foreign_keys = ON;

CREATE TABLE match_runs (
  id TEXT PRIMARY KEY,
  created_at TEXT NOT NULL,
  batch_id TEXT,
  seed INTEGER NOT NULL,
  home_club_id TEXT NOT NULL,
  away_club_id TEXT NOT NULL,
  home_tactics TEXT NOT NULL,
  away_tactics TEXT NOT NULL,
  summary TEXT NOT NULL,
  artefact_filename TEXT NOT NULL UNIQUE,
  CHECK (seed > 0),
  CHECK (json_valid(home_tactics)),
  CHECK (json_valid(away_tactics)),
  CHECK (json_valid(summary))
);

CREATE INDEX match_runs_created_at_idx ON match_runs(created_at DESC, id DESC);
CREATE INDEX match_runs_batch_id_idx ON match_runs(batch_id, seed);
